### ISSUE TITLE
Subprocess error

### ISSUE THREAD

**Issue by CodexTempus** [AugustKarlstedt/blinkist-scraper#2]
Hello @AugustKarlstedt ,
excellent job and idea since I can collect my blinks offline on my erader but I get this error: 
` File "run.py", line 3, in <module>
    subprocess.run(['scrapy', 'runspider', 'scraper.py', '-o', 'books.json'])
  File "C:\Users\Joe\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Joe\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Joe\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Maybe an issue with new python version ?

**Comment by AugustKarlstedt** [comment]
Hi @CodexTempus 

Yes, it may be an error with the new Python version. Unfortunately I don't have time to address this at the moment, so as a workaround, you can try running the commands sequentially in a command prompt window like so:

`scrapy runspider scraper.py -o books.json`

if that doesn't work, then scrapy is not on your PATH and that's what is causing issues. 

After that command completes, you can then run:

`python generate-html.py`

**Comment by CodexTempus** [comment]
Thanks @AugustKarlstedt , i did manage to fix it, i have been looking around a bit to fix up a few things, trying to merge this with another scraper (audio blinks)

**Comment by metromark** [comment]
@CodexTempus how did you solve this issue?

**Comment by lakipn** [comment]
@metromark @AugustKarlstedt I'm also about to make a scraper for both textual and audio blinks. I couldn't find a repo on GitHub that does both things and doing it without bugs (preferably in Python 3, using Scrapy). My yearly premium subscription is expiring in a few days and I'm kinda in a hurry to download some books I haven't listened to or read. So if you're interested, we can collaborate on creating the scraper. :)

**Comment by AugustKarlstedt** [comment]
It should be fairly simple to modify the script to grab the audio files in
addition to the text. Unfortunately I no longer have a subscription, but
please fork and try it out!

Good luck 😊
